### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle#74]
If you attempt to run this repo on Windows, you'll get complaints about missing partials (specifically `drizzle.swatch` for me). Possibly something unix-centric about the way partial paths are generated?

**Comment by jralison** [comment]
Found same problem on Windows 10, with npm 3.9.3 and node v6.2.1.

**Comment by erikjung** [comment]
@tylersticka Can you provide the error output?

I'm assuming this to be a builder issue, but didn't see anything obvious in the areas dealing with partial registration.

**Comment by jralison** [comment]
```
PS D:\www\default\drizzle-master> npm start

> drizzle@0.0.1-alpha prestart D:\www\default\drizzle-master
> npm install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

> drizzle@0.0.1-alpha start D:\www\default\drizzle-master
> gulp --dev

(node:15748) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[03:18:43] Using gulpfile D:\www\default\drizzle-master\gulpfile.js
[03:18:43] Starting 'drizzle'...
[03:18:43] Starting 'copy'...
[03:18:43] Starting 'css:drizzle'...
[03:18:43] Starting 'css:toolkit'...
[03:18:43] Starting 'js'...
[03:18:45] Finished 'copy' after 2.33 s
[03:18:52] Finished 'css:drizzle' after 9.79 s
[03:18:54] 'drizzle' errored after 12 s
[03:18:54] Error: The partial drizzle.swatch could not be found
    at Object.invokePartial (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:266:11)
    at Object.invokePartialWrapper [as invokePartial] (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:68:39)
    at eval (eval at createFunctionContext (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:6:28)
    at prog (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:219:12)
    at execIteration (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:51:19)
    at Array.<anonymous> (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:61:13)
    at eval (eval at createFunctionContext (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:8:31)
    at prog (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:219:12)
    at execIteration (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:51:19)
    at Object.<anonymous> (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:73:15)
    at eval (eval at createFunctionContext (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:8:31)
    at Object.prog [as fn] (D:\www\default\drizzle-master\node_modules\handlebars\dist\cjs\handlebars\runtime.js:219:12)
    at fn (D:\www\default\drizzle-master\node_modules\handlebars-layouts\index.js:41:17)
    at Object.applyAction (D:\www\default\drizzle-master\node_modules\handlebars-layouts\index.js:54:11)
    at Array.reduce (native)
    at Object.helpers.block (D:\www\default\drizzle-master\node_modules\handlebars-layouts\index.js:171:43)
[03:18:54] Finished 'css:toolkit' after 12 s
[03:18:55] Finished 'js' after 12 s

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\bin\\nodejs\\node.exe" "D:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! drizzle@0.0.1-alpha start: `gulp --dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drizzle@0.0.1-alpha start script 'gulp --dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the drizzle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs drizzle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls drizzle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\www\default\drizzle-master\npm-debug.log
```

**Comment by tylersticka** [comment]
@jralison Thank you!

@erikjung That's the same error I was seeing.

**Comment by erikjung** [comment]
After digging into this a bit, I've found that this is indeed a builder issue (https://github.com/cloudfour/drizzle-builder/issues/96) and that this affects _all_ partials. For reasons TBD, the code that constructs the partials "paths" is failing to provide the expected `drizzle.` prefix on Windows.

**Comment by erikjung** [comment]
@tylersticka 

> Possibly something unix-centric about the way partial paths are generated?

Kinda, yeah.

https://github.com/cloudfour/drizzle-builder/issues/96#issuecomment-225672010

**Comment by tylersticka** [comment]
The latest `master` is working for me now. 👍 

Tested on my home PC build running the latest Windows 10, node 4.2.1 and npm 3.3.10.
